# (delete the above line to manage this file manually)

name: Build and Deploy
on:
  # # Runs on pull requests
  # pull_request:
  #     branches: ["*"]
  # # Runs on pushes to main
  # push:
  #     branches: ["main"]
  # Runs on demand
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: oscarlevin/pretext:small

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: add gh-cli
        run: |
          apt-get update
          apt-get install gh jq -y

      - name: setup git config
        run: |
          git config --global --add safe.directory $(pwd)
          git config user.name "${{ github.actor }} via GitHub Actions"
          git config user.email "${{ github.actor }}@github_actions.no_reply"

      - name: install deps
        run: pip install -r requirements.txt --break-system-packages

      - name: install local ptx files
        run: pretext --version

      - name: build deploy targets
        run: pretext build --deploys

      - name: run deploy
        run: pretext deploy --no-push

      - name: push gh-pages branch
        run: git push origin gh-pages
        